services:

  nginx:
    image: nginx
    container_name: nginx_cont
    working_dir: /usr/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/static:/usr/nginx/static
    ports:
      - "8080:80"
    networks:
      - proxy-network

  database:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/etc/local.ini:/opt/couchdb/etc/local.ini
    networks:
      - database-network

  node:
    build: ./node
    container_name: node_cont
    working_dir: /usr/node
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
    volumes: 
      - ./node/src:/usr/node/src
    ports:
      - "4000:4000"
    networks:
      - proxy-network
      - database-network
  
networks:
  proxy-network:
    driver: bridge
  database-network:
    driver: bridge