name: Docker Image CI

on:
  push

jobs:

  compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d
    - name: containers list
      run: docker ps
    - name: wait for service to be up and running
      run: sleep 10s
      shell: bash
    - name: test api and server
      run: npm test --prefix ./node

  #test:
  #  needs: compose
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Test node server and api
  #    run: npm test --prefix ./node
